### ISSUE TITLE
Can you upload the original file that is not normalized, from the 'labeled' file?

### ISSUE THREAD

**Issue by jason2133** [laboratorioAI/polidriving#1]
Hi, Thank you for providing this dataset.
I am really impressed with the opportunity to work with real driving data.

I am currently reviewing your labeled file.
It seems that the labeled file in the 'labeled' folder is normalized, is that correct?

I would like to check the original data before normalization.
Could you please upload the original file, without normalization applied, to this GitHub repository?

Best regards,

**Comment by pablomarcillo** [comment]
Hello Jaeseung

Thanks for your comment about using our dataset. About your question, yes, that data file is normalized. Today, I will upload two unnormalized data files. The first one (20240208-120000_vld.csv) is a labeled data file verified by an expert, and the second one (20240208-120000_lss.csv) is the labeled data file obtained after performing a semi-supervised model. We used the first data file to label the second one using semi-supervised learning.

Feel free to let me know if you have any questions or requests.

Best regards,

Pablo

________________________________
From: Jaeseung Lee ***@***.***>
Sent: Tuesday, September 24, 2024 8:41 PM
To: laboratorioAI/polidriving ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [laboratorioAI/polidriving] Can you upload the original file that is not normalized, from the 'labeled' file? (Issue #1)


Hi, Thank you for providing this dataset.
I am really impressed with the opportunity to work with real driving data.

I am currently reviewing your labeled file.
It seems that the labeled file in the 'labeled' folder is normalized, is that correct?

I would like to check the original data before normalization.
Could you please upload the original file, without normalization applied, to this GitHub repository?

Best regards,

**Comment by jason2133** [comment]
Hello Pablo,
Thank you for uploading the unnormalized data files to the GitHub repository. 
As the problem has been resolved, I will now close this issue.
Thank you again for responding to the request.

Best regards,
Jaeseung
